# Generated by Django 4.2.3 on 2023-07-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('useranme', models.CharField()),
                ('password', models.CharField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('level', models.IntegerField(default=1, max_length=2)),
            ],
        ),
    ]
