# Generated by Django 4.2.3 on 2023-07-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_ticket_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
    ]
